### ISSUE TITLE
Issue during the installation of sf-package in R

### ISSUE THREAD

**Issue by bertrand0007** [oliviergimenez/intro_spatialR#2]
I tried to install the sf-package in my rstudio and this is what I got:

Warning in install.packages :
  downloaded length 11156552 != reported length 27995306
Warning in install.packages :
  URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/sf_1.0-13.zip': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/windows/contrib/4.2/sf_1.0-13.zip' failed
Warning in install.packages :
  le téléchargement du package ‘sf’ a échoué

Can someone help?

**Comment by oliviergimenez** [comment]
Hi Bertrand,
Dunno, and I'm not on Windows so I'm useless. The "Timeout of 60 seconds was reached" suggest that you might have a connexion problem? Maybe try again, or from another place. Other option would be to ask the question directly to the sf package maintainer through https://github.com/r-spatial/sf. 
Good luck,
Olivier
